### PR TITLE
Bump ZeroClipboard to version 2.2.0

### PR DESCRIPTION
**Pull request by n-rodriguez**

### CODE REVIEW

**Comment by gvlekke** [comment]
black box test and it works :)

**Comment by GeoffTidey** [comment]
Works for me as well.   
using 
```gem 'zeroclipboard-rails', github: 'n-rodriguez/zeroclipboard-rails', branch: 'update_zc'```

Can someone please merge & update the gem?  :+1:

**Comment by aeksco** [comment]
:+1:

**Comment by jubrad** [comment]
:+1: Works for me. Could you please merge and update?

**Comment by GeoffTidey** [comment]
Maybe @myitcv or @handtrix could assist or pass the message on to the correct maintainer?

**Comment by n-rodriguez** [comment]
Any news?

**Comment by HaNdTriX** [comment]
https://rubygems.org/gems/zeroclipboard-rails/versions/0.1.1

**Comment by n-rodriguez** [comment]
Thanks :+1:

**Pull request merged**
